### ISSUE TITLE
plugin does not work

### ISSUE THREAD

**Issue by DataGreed** [apiaryio/api-blueprint-sublime-plugin#10] opened 2014-08-18 07:54 UTC
I have markdown extended installed, snowcrash installed, monokai extended install, but still the only thing this plugin highlits is "HOST".

Here's the screenshot
![2014-08-16 0 36 12](https://cloud.githubusercontent.com/assets/2033163/3938630/0fe21c30-24bc-11e4-9749-ad36b8f3e0db.png)

**Comment by austerus** [comment] 2015-01-23 08:01
Same here,
snowcrash 0.16.1
Sublime Text 3 (build 3065)
python 2.7.6

plugin generates AST (says it's ok), I set the syntax to "API Blueprint", it saves a new file with extension "apib" but not syntax highlighting.

I have SublimeLinter installed, as well as linting for various languages (coffee script, php, markdown)

**Comment by Almad** [comment] 2015-02-28 10:36
@DataGreed @austerus may I ask whether this is happening when the blueprint contains latin characters only, or whether this only happens when using cyrillic script? //cc @zdne 

Thanks!

**Comment by DataGreed** [comment] 2015-02-28 15:35
Nah, same thing:

![2015-02-28 18 35 29](https://cloud.githubusercontent.com/assets/2033163/6426675/9d39dea4-bf78-11e4-8d2b-5e272b13f746.png)

**Comment by jmdacruz** [comment] 2015-03-30 21:04
Same here, the plugin generates AST and says it's ok, but the syntax highlighting doesn't work. Using Sublime 3 (build 3083)

**Comment by zdne** [comment] 2015-03-31 13:56
Hm I will have to look into it. If I recall correctly there was something about non-standard Markdown highlighter... will keep you posted

**Comment by danielgtaylor** [comment] 2015-04-21 21:50
@DataGreed, @myklwelch, @austerus, @jmdacruz: I have just tried this with a fresh install of Sublime Text 3. These are the plugins I have:

- Markdown Extended 2015.03.10
- Monokai Extended 2015.03.29
- API Blueprint 2015.03.13

Sample blueprint text:
```markdown
FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# API
This is my API.

# Resource [/resource_path?some_arg]
## Retrieve [GET]
This is some `markdown`. I am a __test__.

+ Response 200

    + Body

            {
                "I": "Am some JSON"
            }
```

Below are renderings of Sublime using two different syntax options and Apiary.io's highlighter. You can set the color scheme via Sublime Text -> Preferences -> Color scheme. You can manually set the syntax with the button at the very bottom right of any Sublime window or with Cmd+Shift+P "Set Syntax: <NAME>".

**API Blueprint syntax, Monokai color scheme (default)**
![screen shot 2015-04-21 at 14 45 12](https://cloud.githubusercontent.com/assets/106826/7263299/371a6e00-e835-11e4-9c08-48fc11cef018.png)

**API Blueprint syntax, Monokai Extended color scheme**:
![screen shot 2015-04-21 at 14 29 28](https://cloud.githubusercontent.com/assets/106826/7263104/9f1ec908-e833-11e4-9c6f-4f2076c1a6cb.png)

**Markdown Extended syntax, Monokai Extended color scheme**:
![screen shot 2015-04-21 at 14 29 59](https://cloud.githubusercontent.com/assets/106826/7263107/a6551ec0-e833-11e4-962c-f047d3adf1d7.png)

**Apiary.io comparison, Monokai Extended color scheme**:
![screen shot 2015-04-21 at 14 30 09](https://cloud.githubusercontent.com/assets/106826/7263110/ab50f480-e833-11e4-80fc-bb7fd264452f.png)

You **must** use a color scheme that supports the extra Markdown attributes like Monokai Extended. Notice that both API Blueprint and the Markdown Extended (and Markdown) syntaxes do not handle the resource path properly, and the API Blueprint syntax is missing support for inline code. Everything seems to be supported on Apiary.io.

Can any of you confirm these results? I am unable to reproduce the original issue regardless of cyrillic character use.

**Comment by DataGreed** [comment] 2015-04-22 06:59
Wait, your screenshots just display the usual markdown bighlighting,
nothing apiblueprint special, even underscored part in the endpoint is
highlighted, is it supposed to. E so? If yes, then I cannot really
understand what is the added value of this extension...

среда, 22 апреля 2015 г. пользователь Daniel G. Taylor написал:

> @DataGreed <https://github.com/DataGreed>, @myklwelch
> <https://github.com/myklwelch>, @austerus <https://github.com/austerus>,
> @jmdacruz <https://github.com/jmdacruz>: I have just tried this with a
> fresh install of Sublime Text 3. These are the plugins I have:
>
>    - Markdown Extended 2015.03.10
>    - Monokai Extended 2015.03.29
>    - API Blueprint 2015.03.13
>
> Sample blueprint text:
>
> FORMAT: 1A
> HOST: http://polls.apiblueprint.org/
> # API
> This is my API.
> # Resource [/resource_path?some_arg]## Retrieve [GET]
> This is some `markdown`. I am a __test__.
> + Response 200
>
>     + Body
>
>             {
>                 "I": "Am some JSON"
>             }
>
> Below are renderings of Sublime using two different syntax options and
> Apiary.io's highlighter. You can set the color scheme via Sublime Text ->
> Preferences -> Color scheme. You can manually set the syntax with the
> button at the very bottom right of any Sublime window or with Cmd+Shift+P
> "Set Syntax: ".
>
> *API Blueprint syntax, Monokai color scheme (default)*
> [image: screen shot 2015-04-21 at 14 45 12]
> <https://cloud.githubusercontent.com/assets/106826/7263299/371a6e00-e835-11e4-9c08-48fc11cef018.png>
>
> *API Blueprint syntax, Monokai Extended color scheme*:
> [image: screen shot 2015-04-21 at 14 29 28]
> <https://cloud.githubusercontent.com/assets/106826/7263104/9f1ec908-e833-11e4-9c6f-4f2076c1a6cb.png>
>
> *Markdown Extended syntax, Monokai Extended color scheme*:
> [image: screen shot 2015-04-21 at 14 29 59]
> <https://cloud.githubusercontent.com/assets/106826/7263107/a6551ec0-e833-11e4-962c-f047d3adf1d7.png>
>
> *Apiary.io comparison, Monokai Extended color scheme*:
> [image: screen shot 2015-04-21 at 14 30 09]
> <https://cloud.githubusercontent.com/assets/106826/7263110/ab50f480-e833-11e4-80fc-bb7fd264452f.png>
>
> You *must* use a color scheme that supports the extra Markdown attributes
> like Monokai Extended. Notice that both API Blueprint and the Markdown
> Extended (and Markdown) syntaxes do not handle the resource path properly,
> and the API Blueprint syntax is missing support for inline code. Everything
> seems to be supported on Apiary.io.
>
> Can any of you confirm these results? I am unable to reproduce the
> original issue regardless of cyrillic character use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apiaryio/api-blueprint-sublime-plugin/issues/10#issuecomment-94953564>
> .
>


-- 
Sincerely,
Alexey.

**Comment by pksunkara** [comment] 2015-04-22 15:00
@DataGreed This extension also parses your blueprint while writing it and shows you any errors it might contain.

**Comment by zdne** [comment] 2015-04-27 02:31
@DataGreed – @danielgtaylor have updated the package to add Blueprint-specific syntax highlighting. Please see #15. Closing this issue. Please feel free to reopen if needed.

**Closed by zdne** 2015-04-27 02:31 UTC
